net start "Alerter"
net start "Computer Browser"
net start "COM+ System Application"
net start "Cryptographic Services"
net start "DHCP Client"
net start "Distributed File System"
net start "Distributed Link Tracking Client"
net start "Distributed Link Tracking Server"
net start "DNS Client"
net start "Event Log"
net start "IPSEC Services"
net start "License Logging"
net start "Logical Disk Manager"
net start "Messenger"
net start "Net Logon"
net start "Netowrk Connections"
net start "NT LM Security Support Provider"
net start "Plug and Play"
net start "Remote Procedure Call (RPC)"
net start "Remote Procedure Call (RPC) Locator"
net start "Remote Registry
net start "Removable Storage"
net start "Security Accounts Manager"
net start "Server"
net start "Task Scheduler"
net start "TCP/IP NetBIOS Helper"
net start "Telephony"
net start "Windows Management Instrumentation Driver Extensions"
net start "Windows Time"
net start "Workstation"
 